name: "Build Release"
on:
  workflow_call:
    inputs:
      mod_name:
      	required: true
        type: string
      minecraft_version:
        required: true
        type: string
      version:
        required: true
        type: string
      forge-cf-id:
        required: true
        type: string
      forge-dependencies:
        required: false
        type: string
      fabric-dependencies:
        required: false
        type: string
      fabric-cf-id:
        required: true
        type: string
      modrinth-id:
        required: true
        type: string
      java-version:
        type: string
        default: 17
    secrets:
      CF_API_TOKEN:
        required: true
      MODRINTH_TOKEN:
        required: true
      DISCORD_WEBHOOK_URL:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with: { fetch-depth: 0 }
      - name: "Set up JDK"
        uses: actions/setup-java@v2
        with: { distribution: "temurin", java-version: ${{ inputs.java-version }} }
      - name: Build with Gradle
        uses: burrunan/gradle-cache-action@v1
        id: build
        with:
          arguments: "setupGithubActions build"
          gradle-version: "wrapper"
      - name: "Create a Release"
        id: create_release
        uses: meeDamian/github-release@2.0
        with:
          files: "Fabric/build/libs/${{ inputs.mod_name }}-fabric-${{ inputs.minecraft_version }}-${{ inputs.version }}.jar Forge/build/libs/${{ inputs.mod_name }}-forge-${{ inputs.minecraft_version }}-${{ inputs.version }}.jar"
          gzip: false
          name: "${{ inputs.mod_name }}-${{ inputs.version }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Publish-Forge"
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          curseforge-id: ${{ inputs.forge-cf-id }}
          curseforge-token: ${{ secrets.CF_API_TOKEN }}
          modrinth-id: ${{ inputs.modrinth-id }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: forge
          version: ${{ inputs.version }}
          files: "Forge/build/libs/${{ inputs.mod_name }}-forge-${{ inputs.minecraft_version }}-${{ inputs.version }}.jar"
          name: "${{ inputs.mod_name }}-forge-${{ inputs.minecraft_version }}-${{ inputs.version }}.jar"
          dependencies: ${{ inputs.forge-dependencies }}
      - name: "Publish-Fabric-Curseforge"
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          curseforge-id: ${{ inputs.fabric-cf-id }}
          curseforge-token: ${{ secrets.CF_API_TOKEN }}
          modrinth-id: ${{ inputs.modrinth-id }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: fabric
          version: ${{ inputs.version }}
          files: "Fabric/build/libs/${{ inputs.mod_name }}-fabric-${{ inputs.minecraft_version }}-${{ inputs.version }}.jar"
          name: "${{ inputs.mod_name }}-fabric-${{ inputs.minecraft_version }}-${{ inputs.version }}.jar"
          dependencies: ${{ inputs.fabric-dependencies }}
      - name: "Build Success"
        id: build-success
        uses: itsmeow/webhook-action@master
        env:
          WEBHOOK_URL: "${{ secrets.DISCORD_WEBHOOK_URL }}"
          data: '{"embeds":[{"title":"${{ inputs.mod_name }} Release Build","url":"https://github.com/${{ github.repository }}/releases/tag/${{ inputs.minecraft_version }}-${{ inputs.version }}","description":"Tag: ${{ inputs.version }}\nStatus: Successful","color":65280,"author":{"name":"${{ github.event.user.login }}","url":"${{ github.event.user.html_url }}","icon_url":"${{ github.event.user.avatar_url }}"}}]}'
      - name: "Build Fail"
        id: build-fail
        uses: itsmeow/webhook-action@master
        if: failure()
        env:
          WEBHOOK_URL: '${{ secrets.DISCORD_WEBHOOK_URL }}\'
          data: '{"embeds":[{"title":"${{ inputs.mod_name }} Release Build","url":"https://github.com/${{ github.repository }}/releases/tag/${{ inputs.minecraft_version }}-${{ inputs.version }}","description":"Tag: ${{ inputs.version }}\nStatus: Failed","color":16711680,"author":{"name":"${{ github.event.user.login }}","url":"${{ github.event.user.html_url }}","icon_url":"${{ github.event.user.avatar_url }}"}}]}'
