name: build
on:
  workflow_call:
    inputs:
      java-version:
        type: string
        default: "17"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with: { fetch-depth: 1 }
      - name: "Set up JDK"
        uses: actions/setup-java@v2
        with: { distribution: "temurin", java-version: "${{ inputs.java-version }}" }
      - name: Give gradle exec permission
        run: "chmod +x gradlew"
      - name: Build with Gradle
        id: build        
        run: "./gradlew setupGithubActions build"
      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: |
            Forge/build/libs/
            Fabric/build/libs/
            build/libs/
            forge/build/libs/
            fabric/build/libs/
            neoforge/build/libs/