name: "Build Release"
on:
  workflow_call:
    inputs:
      fabric-cf-id:
        required: true
        type: string
      fabric-dependencies:
        required: false
        type: string
      modrinth-id:
        required: true
        type: string
      java-version:
        type: string
        default: "17"
    secrets:
      CF_API_TOKEN:
        required: true
      MODRINTH_TOKEN:
        required: true
      DISCORD_WEBHOOK_URL:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with: { fetch-depth: 1 }
      - name: "Set up JDK"
        uses: actions/setup-java@v3
        with: { distribution: "temurin", java-version: "${{ inputs.java-version }}" }
      - name: Give gradle exec permission
        run: "chmod +x gradlew"
      - name: Build with Gradle
        id: build        
        run: "./gradlew setupGithubActions build"
      - name: "Create a Release"
        id: create_release
        uses: meeDamian/github-release@2.0
        with:
          files: "build/libs/${{ steps.build.outputs.mod_name }}-fabric-${{ steps.build.outputs.minecraft_version }}-${{ steps.build.outputs.version }}.jar"
          gzip: false
          name: "${{ steps.build.outputs.mod_name }}-${{ steps.build.outputs.minecraft_version }}-${{ steps.build.outputs.version }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Publish-Fabric-Curseforge"
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: ${{ inputs.fabric-cf-id }}
          curseforge-token: ${{ secrets.CF_API_TOKEN }}
          modrinth-id: ${{ inputs.modrinth-id }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: fabric
          version: ${{ steps.build.outputs.version }}
          files: "build/libs/${{ steps.build.outputs.mod_name }}-fabric-${{ steps.build.outputs.minecraft_version }}-${{ steps.build.outputs.version }}.jar"
          name: "${{ steps.build.outputs.mod_name }}-fabric-${{ steps.build.outputs.minecraft_version }}-${{ steps.build.outputs.version }}.jar"
          dependencies: ${{ inputs.fabric-dependencies }}
      - name: "Build Success"
        id: build-success
        uses: itsmeow/webhook-action@master
        env:
          WEBHOOK_URL: "${{ secrets.DISCORD_WEBHOOK_URL }}"
          data: '{"embeds":[{"title":"${{ steps.build.outputs.mod_name }} Build Released","url":"https://github.com/${{ github.repository }}/releases/tag/${{ steps.build.outputs.minecraft_version }}-${{ steps.build.outputs.version }}","description":"Tag: ${{ steps.build.outputs.minecraft_version }}-${{ steps.build.outputs.version }}","color":65280,"author":{"name":"${{ github.event.user.login }}","url":"${{ github.event.user.html_url }}","icon_url":"${{ github.event.user.avatar_url }}"}}]}'
      - name: "Build Fail"
        id: build-fail
        uses: itsmeow/webhook-action@master
        if: failure()
        env:
          WEBHOOK_URL: '${{ secrets.DISCORD_WEBHOOK_URL }}\'
          data: '{"embeds":[{"title":"${{ steps.build.outputs.mod_name }} Build Failed","url":"https://github.com/${{ github.repository }}/releases/tag/${{ steps.build.outputs.minecraft_version }}-${{ steps.build.outputs.version }}","description":"Tag: ${{ steps.build.outputs.minecraft_version }}-${{ steps.build.outputs.version }}","color":16711680,"author":{"name":"${{ github.event.user.login }}","url":"${{ github.event.user.html_url }}","icon_url":"${{ github.event.user.avatar_url }}"}}]}'
